### ISSUE TITLE
Exit immediately on error

### ISSUE THREAD

**Issue by barrjam** [digitc1/AWSLandingZone#101]
I notice the scripts run to completion and exit with a 0 (SUCCESS) code even when commands fail.

I suggest adding the  'set '-e' option  (https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)

Add '-e' to the first line of each script
 #! /bin/bash -e

The following should do a search and replace for all files:

$ sed -i -e 's!bin/bash!bin/bash -e!' *.sh */*.sh

**Comment by silavjy** [comment]
Upcoming LZ will implement a different deployment approach, issue won't be fixed on this version
