### ISSUE TITLE
Quality - LZ health check - recurring job

### ISSUE THREAD

**Issue by neisije** [digitc1/AWSLandingZone#94]
**Description of the issue:**

For various reasons, services deployed by the LZ are not deployed anymore or in a failed state. 
The objective is to develop a recurring job (most probably a lambda) that will be deployed in the master account of the organization, that will check the status of the services deployed by the LZ on the seclog accounts.

These checks could be (non exhaustive list):
* guardduty status (all regions)
* security hub status (all regions)
* alarms status
* correlate the linked account ID list of a service (guardduty, securityhub) with the logs that should exist in S3

The script used during the initial deployment of the LZ can also be used as a starting point for this health check.

**Comment by silavjy** [comment]
is duplicated by #186. Closing
